server:
  port: 18080
  tomcat:
    max-threads: 1000
spring:
  application:
    name: boot-auth
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 30MB
  mvc:
    servlet:
      load-on-startup: 1
